from django.contrib import admin
from .models import Album, Song, Addresses, Affiliates, Countries, Emails, Gamegifts, Games, Gifttrails, Gifttypes, Gifts, Github, Integrations, Messages, Moods, Notificationtypes, Notifications, Phonenumbers, Players, Playersmoods, Prices, Roles, Status, Twillio, Usps
from django.contrib.sites.models import Site

admin.site.register(Album)
admin.site.register(Song)
admin.site.register(Addresses)
admin.site.register(Affiliates)
admin.site.register(Countries)
admin.site.register(Emails)
admin.site.register(Gamegifts)
admin.site.register(Games)
admin.site.register(Gifttrails)
admin.site.register(Gifttypes)
admin.site.register(Gifts)
admin.site.register(Github)
admin.site.register(Integrations)
admin.site.register(Messages)
admin.site.register(Moods)
admin.site.register(Notificationtypes)
admin.site.register(Notifications)
admin.site.register(Phonenumbers)
admin.site.register(Players)
admin.site.register(Playersmoods)
admin.site.register(Prices)
admin.site.register(Roles)
admin.site.register(Status)
admin.site.register(Twillio)
admin.site.register(Usps)
