# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-25 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=45)),
                ('address_2', models.CharField(blank=True, max_length=45, null=True)),
                ('user_id', models.BigIntegerField()),
                ('state_id', models.IntegerField()),
                ('country_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('zip_id', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Affiliates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'Affiliates',
            },
        ),
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('apikey', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'Amazon',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('primary', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('apikey', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'Facebook',
            },
        ),
        migrations.CreateModel(
            name='Gamegifts',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('times_stolen', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'GameGifts',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('starttime', models.DateTimeField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('created', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'Gifts',
            },
        ),
        migrations.CreateModel(
            name='Gifttrails',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'GiftTrails',
            },
        ),
        migrations.CreateModel(
            name='Gifttypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'GiftTypes',
            },
        ),
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'GitHub',
            },
        ),
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('apikey', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'Google',
            },
        ),
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('table_name', models.CharField(max_length=45)),
                ('created', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'Integrations',
            },
        ),
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('attempt', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('ipaddress', models.CharField(max_length=15)),
                ('useragent', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Logins',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, max_length=45, null=True)),
                ('icon', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Moods',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Notificationtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
            options={
                'managed': False,
                'db_table': 'NotificationTypes',
            },
        ),
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=40)),
                ('previous_password', models.CharField(max_length=40)),
                ('last_changed', models.DateTimeField()),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Passwords',
            },
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('apikey', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'Paypal',
            },
        ),
        migrations.CreateModel(
            name='Phonenumbers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=13)),
                ('created', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'PhoneNumbers',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('clock', models.IntegerField()),
                ('turn_number', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Playersmoods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'PlayersMoods',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'managed': False,
                'db_table': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Twillio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('sid', models.CharField(max_length=45)),
                ('auth_token', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'Twillio',
            },
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('apikey', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'Twitter',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=45, null=True)),
                ('profile_image', models.CharField(max_length=45)),
                ('created', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Usps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
            ],
            options={
                'managed': False,
                'db_table': 'USPS',
            },
        ),
    ]
